VM133 websocket.js:85 WebSocket connection to 'wss://6000-firebase-studio-1747855461592.cluster-6vyo4gb53jczovun3dxslzjahs.cloudworkstations.dev/_next/webpack-hmr' failed:
index-Bp1O903q.js:2780
 GET https://6000-firebase-studio-1747855461592.cluster-6vyo4gb53jczovun3dxslzjahs.cloudworkstations.dev/ 500 (Internal Server Error)
index.js:644 Uncaught ModuleBuildError: Module build failed (from ./node_modules/next/dist/build/webpack/loaders/next-swc-loader.js):
Error:   x Unexpected token `div`. Expected jsx identifier
     ,-[/home/user/studio/src/app/(app)/dashboard/page.tsx:980:1]
 977 |
 978 |
 979 |   return (
 980 |     <div className="flex flex-col h-full gap-6">
     :      ^^^
 981 |        <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-2">
 982 |         <div className="flex items-center gap-2 overflow-x-auto pb-2">
 983 |           {boards.map((board, index) => (
     `----

Caused by:
    Syntax Error
    at processResult (/home/user/studio/no…undle5.js:29:407111)
    at <unknown> (/home/user/studio/no…undle5.js:29:408906)
    at <unknown> (/home/user/studio/no…derRunner.js:1:8645)
    at <unknown> (/home/user/studio/no…derRunner.js:1:5019)
    at r.callback (/home/user/studio/no…derRunner.js:1:4039)